### ISSUE TITLE
Loading from a file

### ISSUE THREAD

**Issue by alexzrh** [qorf/curriculum#1]
https://github.com/qorf/curriculum/blob/main/Reference/DataScience/Loading/SourceCode/Main.quorum

I made updates to this file, but I really don't like squashing these two concepts together like this. Do you prefer to ignore the absolute path example, do you like the file as I updated it, or would you prefer for me to split it into two examples (LoadFileInProject and LoadFileAbsolutePath)?

Also, is this a good way to communicate these issues with you? :D

**Comment by andreas-stefik** [comment]
I think nowadays you can just do Load("somefile.csv") and it does it relative. Let's close this issue though and put stuff like this on ops, so it's all in one place. This is probably more in line with a slack message than an issue report, but no worries.
